### ISSUE TITLE
Packaging the project

### ISSUE THREAD

**Issue by yusufsahinhamza** [bitmartexchange/bitmart-python-sdk-api#6]
Hello,

Seems like this project is not a **[packaged python project](https://packaging.python.org/en/latest/tutorials/packaging-projects/)** and not uploaded to **[Python Package Index (PyPI)](https://pypi.org/)**. So it's not possible to get latest changes without cloning the GitHub repository every time. I would like to create a **Pull Request** to package this python project.

**Comment by 11101171** [comment]
Happy to tell you today that we have done the job, thank you for your offer.
